version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    groups:
      backend-python:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "05:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      frontend-npm:
        patterns:
          - "*"
